spring:
  data:
    mongodb:
      host: "localhost" # TODO change accordingly to docker-compose configuration or move entirely to the ENV value
      port: 27017
      database: "examining_platform"
      username: "root" # TODO move to the ENV
      password: "root" # TODO move to the ENV

# TODO Consider making configurable roles
# examining:
#  security:
#    roles:
#      - name: "admin"
